STARTED JOB AT: Mon Jan 16 01:14:42 EST 2023

2023-01-16 01:14:45.139450 (reading meta data, all rows)
Traceback (most recent call last):
  File "clean.py", line 19, in <module>
    meta = pd.read_csv('/n/henrich_lab/Lab/newspaperarchive_metadata/Harvard_FileDetails.txt', sep='|', encoding_errors='ignore')
TypeError: read_csv() got an unexpected keyword argument 'encoding_errors'
FINISHED JOB AT: Mon Jan 16 01:14:45 EST 2023

